# Short term forecasting example:

In [94]:
import pandas as pd
import numpy as np

In [95]:
A = pd.read_csv("C:/Users/Admin/Downloads/Google_Stock_Price_Train.csv")

In [96]:
A

Date    Open    High     Low   Close      Volume
0       1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1       1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2       1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3       1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4       1/9/2012  322.04  322.29  309.46  620.76  11,688,800
...          ...     ...     ...     ...     ...         ...
1253  12/23/2016  790.90  792.74  787.28  789.91     623,400
1254  12/27/2016  790.68  797.86  787.66  791.55     789,100
1255  12/28/2016  793.70  794.23  783.20  785.05   1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79     744,300
1257  12/30/2016  782.75  782.78  770.41  771.82   1,770,000

[1258 rows x 6 columns]

In [97]:
trd = A[["Open"]].values

In [98]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
trd=mm.fit_transform(trd)

In [99]:
trd.shape

(1258, 1)

In [100]:
xtrain = []
ytrain = []
for i in range(50,1258,1):
    xtrain.append(trd[i-50:i])
    ytrain.append(trd[i:i+1])

In [101]:
xtr = np.array(xtrain)
ytr = np.array(ytrain)

In [102]:
xtr.shape

(1208, 50, 1)

In [103]:
ytr.shape

(1208, 1, 1)

In [104]:
from keras.models import Sequential
from keras.layers import Dense,LSTM

In [105]:
nn = Sequential()
nn.add(LSTM(50,return_sequences=True,input_shape=(50,1)))
nn.add(LSTM(100,return_sequences=True))
nn.add(Dense(1))

In [106]:
nn.compile(optimizer="adam",loss="mean_squared_error")
nn.fit(xtr,ytr,epochs=10)

Epoch 1/10
38/38 [==============================] - 4s 32ms/step - loss: 0.0535
Epoch 2/10
38/38 [==============================] - 1s 32ms/step - loss: 0.0171
Epoch 3/10
38/38 [==============================] - 1s 32ms/step - loss: 0.0133
Epoch 4/10
38/38 [==============================] - 1s 32ms/step - loss: 0.0113
Epoch 5/10
38/38 [==============================] - 1s 33ms/step - loss: 0.0101
Epoch 6/10
38/38 [==============================] - 1s 32ms/step - loss: 0.0090
Epoch 7/10
38/38 [==============================] - 1s 32ms/step - loss: 0.0082
Epoch 8/10
38/38 [==============================] - 1s 34ms/step - loss: 0.0076
Epoch 9/10
38/38 [==============================] - 1s 33ms/step - loss: 0.0070
Epoch 10/10
38/38 [==============================] - 1s 33ms/step - loss: 0.0071


In [107]:
tsd = pd.read_csv("C:/Users/Admin/Downloads/Google_Stock_Price_Test.csv")

In [108]:
tsd.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [109]:
Q = pd.concat([A,tsd])
Q.index = range(0,1278)

In [110]:
Q = Q[["Open"]].values

In [111]:
xtest=[]
for i in range(1258,1277,1):
    xtest.append(Q[i-50:i])

In [112]:
xts = np.array(xtest)

In [113]:
xts.shape

(19, 50, 1)

In [114]:
d = nn.predict(xts[18:19])

In [115]:
d = d.reshape(50,1)

In [116]:
mm.inverse_transform(d)

array([[1501.9349],
       [1949.4379],
       [1728.9564],
       [1527.9003],
       [1537.9843],
       [1579.5065],
       [1576.934 ],
       [1559.3887],
       [1549.591 ],
       [1545.5999],
       [1541.9961],
       [1538.0698],
       [1534.7592],
       [1532.2238],
       [1530.2004],
       [1528.532 ],
       [1527.1617],
       [1526.0668],
       [1525.1919],
       [1524.4894],
       [1523.9373],
       [1523.5105],
       [1523.1796],
       [1522.947 ],
       [1522.7572],
       [1522.6133],
       [1522.5007],
       [1522.4178],
       [1522.3573],
       [1522.3024],
       [1522.2765],
       [1522.2599],
       [1522.2595],
       [1522.2357],
       [1522.2135],
       [1522.1735],
       [1522.1255],
       [1522.0842],
       [1522.0609],
       [1522.0514],
       [1522.0503],
       [1522.0481],
       [1522.0477],
       [1522.05  ],
       [1522.049 ],
       [1522.0457],
       [1522.0133],
       [1521.9728],
       [1521.922 ],
       [1521.8959]],

# Getting Gold price for tomorrow:

In [132]:
A = pd.read_csv("C:/Users/Admin/Downloads/monthly.csv")

In [133]:
A

Date     Price
0    1950-01    34.730
1    1950-02    34.730
2    1950-03    34.730
3    1950-04    34.730
4    1950-05    34.730
..       ...       ...
828  2019-01  1291.630
829  2019-02  1319.755
830  2019-03  1302.286
831  2019-04  1287.650
832  2019-05  1282.460

[833 rows x 2 columns]

In [134]:
trd = A[["Price"]].values

In [135]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm.fit_transform(trd)

array([[1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.31717748e-04],
       [1.31717748e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.37444607e-04],
       [1.31717748e-04],
       [1.25990890e-04],
       [1.25990890e-04],
       [1.25990890e-04],
       [1.37444607e-04],
       [9.73565966e-05],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.08810314e-04],
       [1.88986335e-04],
       [1.37444607e-04],
       [2.29074345e-05],
       [4.58148690e-05],
       [5.15417276e-05],
       [1.14537172e-05],
       [8.01760207e-05],
       [1.31717748e-04],
       [1.71805759e-04],
       [2.23347486e-04],
       [2.63435497e-04],
       [2.46254921e-04],
       [2.51981779e-04],


In [136]:
trd.shape

(833, 1)

In [137]:
xtrain=[]
ytrain=[]
for i in range(50,833,1):
    xtrain.append(trd[i-50:i])
    ytrain.append(trd[i:i+1])

In [138]:
xtr = np.array(xtrain)

In [139]:
ytr = np.array(ytrain)

In [140]:
xtr.shape

(783, 50, 1)

In [141]:
ytr.shape

(783, 1, 1)

In [142]:
nn1 = Sequential()
nn1.add(LSTM(50,return_sequences=True,input_shape=(50,1)))
nn1.add(LSTM(100,return_sequences=True))
nn1.add(Dense(1))
nn.compile(optimizer="adam",loss="mean_squared_error")
nn.fit(xtr,ytr,epochs=10)

Epoch 1/10
25/25 [==============================] - 4s 31ms/step - loss: 331646.9688
Epoch 2/10
25/25 [==============================] - 1s 31ms/step - loss: 329778.9375
Epoch 3/10
25/25 [==============================] - 1s 32ms/step - loss: 327934.6875
Epoch 4/10
25/25 [==============================] - 1s 34ms/step - loss: 326113.3750
Epoch 5/10
25/25 [==============================] - 1s 32ms/step - loss: 324312.4062
Epoch 6/10
25/25 [==============================] - 1s 32ms/step - loss: 322509.5625
Epoch 7/10
25/25 [==============================] - 1s 32ms/step - loss: 320748.9688
Epoch 8/10
25/25 [==============================] - 1s 34ms/step - loss: 318998.5938
Epoch 9/10
25/25 [==============================] - 1s 32ms/step - loss: 317273.3438
Epoch 10/10
25/25 [==============================] - 1s 32ms/step - loss: 315525.1562


In [143]:
w = nn.predict(xtr[782:783])

In [144]:
w.shape

(1, 50, 1)

In [145]:
w = w.reshape(50,1)

In [146]:
mm.inverse_transform(w)

array([[ 88378.34 ],
       [111633.586],
       [115196.3  ],
       [115687.14 ],
       [115753.71 ],
       [115762.74 ],
       [115763.95 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [115764.14 ],
       [11576